Repository JudiTeller/S5-VR-game, pull requests merged in 2023-11, with the labels that each got.

#24 Puzzle template
  docs/puzzle/puzzle_template.md
  docs/puzzle/templates/WandPanel/puzzle_buttonRepeat.md
  docs/puzzle/templates/WandPanel/puzzle_buttonSequence.md
  docs/puzzle/templates/WandPanel/puzzle_cable.md
Labels: documentation, enhancement

#32 Game code extension
  Assets/MyPrefabs/Scripts/Game/Tasks/ExampleTask/ExampleGameTask.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/ExampleTask/ExampleTaskFactory.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/ExampleTimerTask.meta
  Assets/MyPrefabs/Scripts/Game/Tasks/ExampleTimerTask/ExampleTaskFactory.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/ExampleTimerTask/ExampleTaskFactory.cs.meta
  Assets/MyPrefabs/Scripts/Game/Tasks/ExampleTimerTask/ExampleTimerGameTask.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/ExampleTimerTask/ExampleTimerGameTask.cs.meta
  Assets/MyPrefabs/Scripts/Game/Tasks/GameTask.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/GameTaskObserver.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/TaskState.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/TaskState.cs.meta
  Assets/MyPrefabs/Scripts/Game/Tasks/TimerTask.cs
  Assets/MyPrefabs/Scripts/Game/Tasks/TimerTask.cs.meta
  docs/puzzle/puzzle_template.md
  docs/puzzle/templates/BookShelf/book-riddle.md
  docs/puzzle/templates/WandPanel/puzzle_buttonRepeat.md
  docs/puzzle/templates/WandPanel/puzzle_buttonSequence.md
  docs/puzzle/templates/WandPanel/puzzle_cable.md
  docs/puzzle/templates/WandPanel/puzzle_marbleGravity.md
  meeting_protocols/2023-11-01.md
Labels: enhancement

#41 Meetingprotocol for weekly meeting (19.11.2023)
  meeting_protocols/2023-11-19.md
Labels: documentation

#62 Adds game end evaluation script to play endscene only if game is won
  Assets/Prefabs/Game/Game.prefab
  Assets/Scenes/SpaceStation.unity
  Assets/Scripts/Environment/DoorController.cs
  Assets/Scripts/Environment/GameStateDoorController.cs
  Assets/Scripts/Environment/GameStateDoorController.cs.meta
  Assets/Scripts/Game/GameInformation.cs
  Assets/Scripts/Game/GameInformation.cs.meta
  Assets/Scripts/Game/GameState.cs
  Assets/Scripts/Game/GameState.cs.meta
  Assets/Scripts/Game/GameTimer.cs
  Assets/Scripts/Timeline/PlayEndscene.cs
Labels: enhancement
