Repository JudiTeller/S5-VR-game, pull requests merged in 2024-01, with the labels that each got.

#115 [UI] alternative navigation markers
  .attach_pid197241
  Assets/Materials/UI.meta
  Assets/Materials/UI/MarkerInnerGreen.mat
  Assets/Materials/UI/MarkerInnerGreen.mat.meta
  Assets/Materials/UI/MarkerInnerOrange.mat
  Assets/Materials/UI/MarkerInnerOrange.mat.meta
  Assets/Materials/UI/MarkerInnerRed.mat
  Assets/Materials/UI/MarkerInnerRed.mat.meta
  Assets/Materials/UI/MarkerOuter.mat
  Assets/Materials/UI/MarkerOuter.mat.meta
  Assets/Materials/UI/MarkerShader.shader
  Assets/Materials/UI/MarkerShader.shader.meta
  Assets/Prefabs/Game/Tasks/TaskSpawnpoint.prefab
  Assets/Prefabs/UI/Navigator/Alt_marker.prefab
  Assets/Prefabs/UI/Navigator/Alt_marker.prefab.meta
  Assets/Scenes/SpaceStation.unity
  Assets/Scenes/SpawnpointTestScene.unity
  Assets/Scripts/Game/FactoryInitializationData.cs
  Assets/Scripts/Game/GameHUDService.cs
  Assets/Scripts/Game/GameTimer.cs
  Assets/Scripts/Game/Tasks/GameTask.cs
  Assets/Scripts/Game/Tasks/GameTaskFactory.cs
  Assets/Scripts/Game/Tasks/TaskSpawnPoint.cs
  Assets/Scripts/PlayerController/PlayerProfileService.cs
  Assets/Scripts/UI/HUD.cs
  Assets/Scripts/UI/Navigator/AltMarker.cs
  Assets/Scripts/UI/Navigator/AltMarker.cs.meta
  Assets/Textures/UI/marker.fbx
  Assets/Textures/UI/marker.fbx.meta
Labels: enhancement

#120 Missing game id display fix
  Assets/Scripts/Game/Metrics/MetricCollector.cs
Labels: bug

#126 Testing changes into develop
  Assets/Prefabs/Game/Game.prefab
  Assets/Prefabs/Game/Tasks/AsteroidShooter/AsteroidShooter.prefab
  Assets/Prefabs/Game/Tasks/Button_testing/ButtonDesk.prefab
  Assets/Prefabs/Game/Tasks/EnergyCore/EnergyCorePrefab.prefab
  Assets/Prefabs/Game/Tasks/GameExit.meta
  Assets/Prefabs/Game/Tasks/GameExit/GameExit.prefab
  Assets/Prefabs/Game/Tasks/GameExit/GameExit.prefab.meta
  Assets/Prefabs/Game/Tasks/MedicalDisaster/MedicalDisaster.prefab
  Assets/Prefabs/Game/Tasks/MixingIngredients/MixingIngredients.prefab
  Assets/Prefabs/Game/Tasks/MixingIngredients/PlantToWater.prefab
  Assets/Prefabs/Game/Tasks/TaskSpawnpoint.prefab
  Assets/Prefabs/Game/Tasks/book_riddle/book_riddle_prefab.prefab
  Assets/Prefabs/Game/Tasks/leaks_riddle/leaks_riddle.prefab
  Assets/Prefabs/Game/Tasks/marble_gravity/easy_labyrinth.prefab
  Assets/Prefabs/Game/Tasks/marble_gravity/hard_labyrinth.prefab
  Assets/Prefabs/Game/Tasks/marble_gravity/medium_labyrinth.prefab
  Assets/Prefabs/Player/PlayerProfile.prefab
  Assets/Prefabs/UI/HUD_Canvas.prefab
  Assets/Scenes/SpaceStation.unity
  Assets/Scenes/SpawnpointTestScene.unity
  Assets/Scripts/Game/Difficulty.cs
  Assets/Scripts/Game/GameEndProcedure.cs
  Assets/Scripts/Game/GameEndProcedure.cs.meta
  Assets/Scripts/Game/GameHUDService.cs
  Assets/Scripts/Game/GameTimer.cs
  Assets/Scripts/Game/Integrity.cs
  Assets/Scripts/Game/Metrics/MetricCollector.cs
  Assets/Scripts/Game/Observer/GameTaskObserver.cs
  Assets/Scripts/Game/Tasks/AsteroidsShooter/AsteroidShooterFactory.cs
  Assets/Scripts/Game/Tasks/AsteroidsShooter/ShootProjectile.cs
  Assets/Scripts/Game/Tasks/AsteroidsShooter/StartAsteroidShooter.cs
  Assets/Scripts/Game/Tasks/BookRiddle/BookRiddle.cs
  Assets/Scripts/Game/Tasks/Button_Puzzle/ButtonSequenceLogic.cs
  Assets/Scripts/Game/Tasks/Button_Puzzle/RubicsCube.cs
  Assets/Scripts/Game/Tasks/EnergyCore/StartEnergyCoreTask.cs
  Assets/Scripts/Game/Tasks/GameExit.meta
  Assets/Scripts/Game/Tasks/GameExit/GameExitTask.cs
  Assets/Scripts/Game/Tasks/GameExit/GameExitTask.cs.meta
  Assets/Scripts/Game/Tasks/GameExit/GameExitTaskFactory.cs
  Assets/Scripts/Game/Tasks/GameExit/GameExitTaskFactory.cs.meta
  Assets/Scripts/Game/Tasks/GameTask.cs
  Assets/Scripts/Game/Tasks/GameTaskType.cs
  Assets/Scripts/Game/Tasks/MedicalDisaster/MedicalDisaster.cs
  Assets/Scripts/Game/Tasks/MixingIngredients/IngredientType.cs
  Assets/Scripts/Game/Tasks/MixingIngredients/MixingIngredients.cs
  Assets/Scripts/Game/Tasks/StorageRiddle/StartStorageRiddle.cs
  Assets/Scripts/Game/Tasks/TimerTask.cs
  Assets/Scripts/Game/Tasks/leaks_riddle/LeaksRiddle.cs
  Assets/Scripts/Game/Tasks/marble_gravity/MarbleGravity.cs
  Assets/Scripts/Sound/SoundManager.cs
  Assets/Scripts/UI/TextPanel.cs
  Assets/Sound/LicenseInformation.md
  Assets/Sound/sphere_rolling.wav
  Assets/Sound/sphere_rolling.wav.meta
Labels: bug, enhancement
